### PR TITLE
build(spm): add swift package manifest

### PR DESCRIPTION
**Pull request by sherwinski**
This PR introduces the addition of a `Package.swift` manifest, which will allow users to import imgix-swift via the Swift Package Manager. As far as I know, there's no way to test this actually works without the file being checked into the remote repository so I am hoping to get at least one set of experienced eyes on it first. Below are some resources, examples I used when creating this file:
- [swift.org](https://swift.org/package-manager/)
- [Creating a Standalone Swift Package with Xcode](https://developer.apple.com/documentation/xcode/creating_a_standalone_swift_package_with_xcode)
-  [apple/example-package-deckofplayingcards](https://github.com/apple/example-package-deckofplayingcards/blob/master/Package.swift)
- [Example of OSS project with SPM, Carthage & Cocoapods support?](https://forums.swift.org/t/example-of-oss-project-with-spm-carthage-cocoapods-support/28001)
- [Alamofire's Package.swift](https://github.com/Alamofire/Alamofire/blob/master/Package.swift)

### CODE REVIEW

**Comment by sherwinski** [comment]
Hello @ikait 👋 

I am trying to enable our users to import this project with SPM. I would love to get your opinion on how this `Package.swift` is organized and any issues/best practices you think I might have missed in the process. Thank you

**Comment by ikait** [comment]
Hello @sherwinski,

This is a great PR we've been waiting for. Indeed, we've already used ImgixSwift I forked and made it support SPM in our projects so I can provide some tips for this. These changes are almost good but some points will cause a import error as follows:

- platforms: [SPM doesn't have tvOS(.v9_2) as a supported version](https://developer.apple.com/documentation/swift_packages/supportedplatform/tvosversion) so you can specify [`tvOS("9.2")`](https://developer.apple.com/documentation/swift_packages/supportedplatform/3112762-tvos) or choose a v9 or v10.
- sources: SPM cannot import a target with source files contains mixed language so you can add a new target for NSString+ImgixSwiftMd5.h as [like this page](http://ankit.im/swift/2016/05/21/creating-objc-cpp-packages-with-swift-package-manager/) instructed. Or, rewrite it with Swift. In my forked project, I chose the rewrite way because the code is not so heavy.

**Comment by sherwinski** [comment]
Thank you @ikait for the insightful feedback and resources! I am trying to split up the library by swift and objc types, but am still working through some build errors at the moment. I may end up ultimately rewriting it all in swift, as you mentioned.

On a separate note - now that I can devote more time and attention to library, I would happily review/accept any pull requests for it. Improving imgix-swift is important to us and receiving direct feedback/contributions from its users is extremely valuable in achieving that. Also, you can expect my response time to be faster this time around 😁

**Comment by sherwinski** [comment]
Hello @ikait, I've made a couple of changes in regards to your feedback and I think this is ready for release. Would love to get your thoughts on it especially since it sounds like you have gone through these steps on your own fork. Thank you

**Comment by ikait** [comment]
Hi @sherwinski, I confirmed your changes and I applied ImgIxSwift of this branch to my project. Now it works nicely. Perfect! 💯

**Comment by sherwinski** [comment]
That's great! Thanks again for your help 😁

**Pull request merged**
