### PR TITLE
Swift 3

### PR DESCRIPTION
**Pull request by paulstraw**
Does what it says on the tin.

### CODE REVIEW

**Comment by jndonald3** [comment]
Any time estimation on when this will be released?

**Comment by paulstraw** [comment]
Hey @jndonald3, I suppose it could be released now that Xcode 8 is out of beta. I'll try to get to it this week; looks like there may be some conflicts and such that need to be resolved.

**Comment by paulstraw** [comment]
Should be all good in 0.2.0 @jndonald3. Let me know if you run into any issues.

**Comment by jndonald3** [comment]
Sweet! ill try it out, will let you know if i run into anything!

**Pull request merged**
